on: push

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: abhinayagarwal/cla-verify-gsheets@master
        with:
          spreadsheetId: '1PBCsWr9ladI1idcnt83VjEoouIBkyy310P2M6hwIGb0'
          sheetName: 'Sheet2'
          columnName: 'A'
          searchFor: ${{ github.event.pull_request.user.login }}
          label: 'cla-signed'
          message: 'Please sign CLA'