name: gsheet.action test
on: push

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - id: 'update_worksheet'
        uses: jroehl/gsheet.action@release # you can specify '@release' to always have the latest changes
        with:
          spreadsheetId: 1PBCsWr9ladI1idcnt83VjEoouIBkyy310P2M6hwIGb0
          commands: | # list of commands, specified as a valid JSON string
            [
              { "command": "getData", "args": { "range": "Sheet2!A:A" } }
            ]
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
      - name: Find username
        env:
          #  the output of the action can be found in ${{ steps.update_worksheet.outputs.results }}
          RESULTS: ${{ steps.update_worksheet.outputs.results }}
          # GITHUB_USER_NAME: ${{ github.event.pull_request.user.login }}
          GITHUB_USER_NAME: ${{ github.actor }}
        shell: bash
        run: |
          index=`echo "$RESULTS" | jq -c '.results[].result.rawData | flatten | index(env.GITHUB_USER_NAME)'`
          echo $GITHUB_USER_NAME
          echo $index
          [ "$index" = "null" ] && echo "Username not found"